### PR TITLE
FactoryGirl lint task

### PR DESCRIPTION
**Pull request by jholder-mdsol**
Add the `factory_girl:lint` task to Rake, and run it if available.

Mirrors the changes made in [the branch based off of `v0.2.2`](https://github.com/mdsol/kender/tree/feature/MCC-198243_factory_girl_lint_0_2_2), the last version known to work for SDIS.

Used by [SDIS](https://github.com/mdsol/subject_data_integration/). Related to MCC-198243.

### CODE REVIEW

**Comment by pmavinkurve-mdsol** [comment]
Thanks @jholder-mdsol 
Simply tagging folks right now @jcarres-mdsol @cabbott

**Comment by jholder-mdsol** [comment]
Thanks, @pmavinkurve-mdsol. I wasn't sure who to ping.

**Comment by pmavinkurve-mdsol** [comment]
@jholder-mdsol can you look into resolving the CI failures? ignore me, if you are already doing that. thanks.

**Comment by jholder-mdsol** [comment]
@pmavinkurve-mdsol Confirmed that it's an outstanding issue with `master` branch. It does not impact version 0.2.2, which SDIS was using before and which I used as the base for the custom branch.

**Comment by jcarres-mdsol** [comment]
Can you update the changelog and version files also so we can make a new release?

**Comment by jholder-mdsol** [comment]
@jcarres-mdsol Good catch. Did I get those changes right, here in [this commit](https://github.com/mdsol/kender/commit/2120219f81f7fd4bd06dc085445b3e52546c4836)?

**Comment by jcarres-mdsol** [comment]
https://rubygems.org/gems/kender/versions/0.3.2 ready to use

**Comment by jholder-mdsol** [comment]
@jcarres-mdsol I created a [2.2.1](https://github.com/mdsol/kender/releases/tag/v0.2.2.1) tag for kender. Should a point release be published to rubygems.org for that, as well? I'll test v0.3.2 against SDIS in the meantime.

**Comment by jholder-mdsol** [comment]
@jcarres-mdsol Tried using v0.3.2 with SDIS, but [the SDIS CI build fails](http://ec2-54-90-230-2.compute-1.amazonaws.com:8080/job/sdi-custom/104/console) when I do so. Sticking with v0.2.2.1 for now.

**Comment by jcarres-mdsol** [comment]
@jholder-mdsol  your build is failing because rdlint is detecting a problem with your hypermedia resource.
There is only one file called crichtonerrors but I'm not sure if that really represents any object in your project, most probably not. So crichton is getting confused and  rdlint which is like a hypermedia validator is failing.

**Comment by pmavinkurve-mdsol** [comment]
@jcarres-mdsol we can't use rdlint effectively, and we don't need to use it, because our service currently doesn't have hypermedia API. Unfortunately, our code uses Crichton for error handling, and not easy to remove as a dependency of SDIS. but without this, we are stuck with lower versions of kender. I hope we can update crichton to be forgiving in `rdlint` behavior when there are no real api descriptors present.

**Pull request merged**
