### PR TITLE
Add support for rubocop gem

### PR DESCRIPTION
**Pull request by jprice-mdsol**
Run rubocop as part of CI

### CODE REVIEW

**Comment by jcarres-mdsol** [comment]
I get what you want to achieve here and personally like it but maybe some people would disagree and do not want to impose it via kender if does not make sense for them.
@mdsol/team-10 what do you think?

**Comment by jprice-mdsol** [comment]
This somewhat follows the `reek` example, which is the same sort of tool. The difference is that it can fail the build - because it wasn't completely obvious to me how to get it not to do so.

**Comment by jfeltesse-mdsol** [comment]
The problem I foresee is people moving away from kender because rubocop and the plugin gems you may have (rubocop-rspec...) can be really pedantic. You can disable some cops or define exclusions in your config but for the other cases you'd have to add magic comments in your code to bypass checks for a specific situation where you know it's ok. Or worse, you'd code to please the linter.

For instance in my code I have a spec around the parsing of RSA keys that have been made into a single line to use in 12 factor env vars.
The input is a single line RSA key with "hard" `\n` characters and no termination `\n` character.
The easiest way I could think of defining this input var is by doing this
```
rsa_key = 'hello\n' \
  'there'
puts rsa_key
# => hello\nthere
```
But then in my rubocop config I enforce double quotes. And that makes rubocop angry:
```
cop.rb:2:3: C: Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  'there'
  ^^^^^^^
```
In this case I can't use double quotes because they'd be interpolating the `\n`. And I don't want to do `\\n` or use a squiggly heredoc with a gsub call to replace newlines by `\n`, it's ugly, confusing and it'd be coding to please rubocop.

I'm not sad at having a few failures like this in the code because I _know_ these are legit cases. And sure I could disable that rule for that one line but then it's starting a not-so-great trend.

Don't get me wrong, I like rubocop and I think every project should use it but as for making it mandatory to have a CI to pass is more cons than pros IMHO. Other tools such as Hound can help if people want to be strict about those things.

Oh and on an unrelated note, another drawback of running this in kender is you cannot specify options. The obvious one being the location of the config file which can be passed with `-c` if not present in the standard location. I don't remember so much but I have seen people having a bunch of switches when calling rubocop in their travis file, which makes me think they would have to drop kender altogether to be able to use rubocop as usual. Unless there's a way to tell kender to _not_ run a tool? That would be a cool feature to have, if not there already @jcarres-mdsol.

**Comment by jfeltesse-mdsol** [comment]
@jprice-mdsol @jcarres-mdsol what's the next step according to you guys?

**Pull request closed without merging**
