### PR TITLE
Feature/config deploy

### PR DESCRIPTION
**Pull request by jcarres-mdsol**
@pmavinkurve-mdsol 

Using config:deploy isntead of config:all
The difference between these two tasks is that config:deploy do not ask questions and will overwrite always. It is used by Chef.
I think that's what we want in the CI also, i.e. all automatic uses of dice_bag should use deploy to avoid the problem of stalling the process waiting for input.

The rest of the changes are improvements in docs and gemfile

### CODE REVIEW

**Comment by pmavinkurve-mdsol** [comment]
Thanks @jcarres-mdsol ! This would solve the problem we have in epro-app for a file we have to check in for now.

**Comment by pmavinkurve-mdsol** [comment]
Looks good! Thanks for fixing this so quickly. I am happy with merging after at least one more person reviews it and gives approval. @HonoreDB or @mszenher  @cabbott ?

**Comment by BPONTES** [comment]
looks good

**Comment by jcarres-mdsol** [comment]
@pmavinkurve-mdsol 0.3.0 is out!

**Pull request merged**
