### PR TITLE
remove Crichton lint

### PR DESCRIPTION
**Pull request by jfeltesse-mdsol**
Crichton is dead

Note I intentionally left an empty line at the beginning of the CHANGELOG and I've not bumped the version to try to limit conflicts with https://github.com/mdsol/kender/pull/82

@ejennings-mdsol @jcarres-mdsol @vlazartranscenda

### CODE REVIEW

**Comment by ejennings-mdsol** [comment]
Thanks @jfeltesse-mdsol!  Travis is unhappy

**Comment by jfeltesse-mdsol** [comment]
Thanks, fixed.

**Review by vlazartranscenda — APPROVED** [review]

**Review by ejennings-mdsol — APPROVED** [review]
Thanks @jfeltesse-mdsol!

**Comment by ejennings-mdsol** [comment]
Tagged 0.7.0

**Pull request merged**
